export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const RECEIVE_POSTS_ERROR = 'RECEIVE_POSTS_ERROR';
export const ALL_DATA_TO_FILTER = 'ALL_DATA_TO_FILTER';
export const DATA_FROM_TAG = 'DATA_FROM_TAG';
export const DATA_FROM_INPUT = 'DATA_FROM_INPUT';
